Demo: Grab_ImageCallback.cpp
	g++ -std=c++11 -g -o Grab_ImageCallback Grab_ImageCallback.cpp -I../../../include -Wl,-rpath=../../../lib/64 -L../../../lib/64 -lMvCameraControl


clean:
	rm Grab_ImageCallback -rf
