# below from 5651 $GPFPD
string gps_week
string gps_time
string heading
string pitch
string roll
string latitude
string longitude
string altitude
string vel_east
string vel_north
string vel_up
string baseline
string nsv1_num
string nsv2_num
string status

# below from 5651 $GPGGA
string utc_time
string latitude_gpgga
string longitude_gpgga
string no_sv
string hdop

# below customized
float64 unix_time_minus_gps_time
